library(DNAfusion)


####MonAlec cohort####
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Maiken cohort/PosDeduped")
EML4_ALK_detection("00QWTDYUH1E0VRM8_bl.bam")
EML4_ALK_detection("9XPREVQOLXK3JE4S_bl.bam")
EML4_ALK_detection("CQHQ4QA5K295LU8D_bl.bam")
EML4_ALK_detection("Q54SLTX033G766IM_bl.bam")
EML4_ALK_detection("4M0SDUZCZMWHIYJ7_bl.bam")
EML4_ALK_detection("UE2R8PRMAT4T3IXD_bl.bam")
EML4_ALK_detection("IT8BJVO03C08FV04_bl.bam")
EML4_ALK_detection("YBNHFHWVB0HBC3YY_bl.bam")
EML4_ALK_detection("4OOA9FR46IB4BXBJ_bl.bam")
EML4_ALK_detection("G6M680NTHH1YGZ5A_bl.bam")
EML4_ALK_detection("OUWIO70E08Q51YTB_bl.bam")
EML4_ALK_detection("2UCZEDI4F35T6ILM_bl.bam")
EML4_ALK_detection("PQ9NESTYL82NBF9B_bl.bam")
EML4_ALK_detection("83Z7BF2N4Y12L933_bl.bam")
EML4_ALK_detection("91R09H85UBLFEOLO_bl.bam")
EML4_ALK_detection("K6YFO3FWXOFI99UZ_bl.bam")
EML4_ALK_detection("E3ZSHQ5SSX9YNSUH_bl.bam")
EML4_ALK_detection("YNKZ9UW1EMNM7TQ5_bl.bam")
EML4_ALK_detection("5K04BRIUDO2EMCUM_bl.bam")
EML4_ALK_detection("MJ0ZS032J5A67ZUA_bl.bam")
EML4_ALK_detection("CMM8PC3S8M9NLOCH_bl.bam")
EML4_ALK_detection("UT3Y7U411B7L6GU0_bl.bam")
EML4_ALK_detection("B14Q10RS3BRU807A_bl.bam")
EML4_ALK_detection("YBWTPETM88I7OL5N_bl.bam")
EML4_ALK_detection("AEKYGMNC3109ZI9E_bl.bam")
EML4_ALK_detection("MONA_26.bam")
EML4_ALK_detection("SEAVIJ1HQS7PSXM1_bl.bam")
EML4_ALK_detection("PH7LZCX099H0XGS6_bl.bam")
EML4_ALK_detection("1POXVH7P4YZ0N22P_bl.bam")
EML4_ALK_detection("885S9KA6LW9I28H9_bl.bam")
EML4_ALK_detection("YZ0PPZ1A5JLCB27C_bl.bam")
EML4_ALK_detection("MONA_32.bam")
EML4_ALK_detection("MONA_33.bam")
EML4_ALK_detection("72EP6S90YZWUFGRT_bl.bam")
EML4_ALK_detection("6KYRWVT7W2KW1U48_bl.bam")
EML4_ALK_detection("UOOXOPI9BOLDIU56_bl.bam")
EML4_ALK_detection("40U550ULPLYA0U5D_bl.bam")
EML4_ALK_detection("9Y6DEL9FY4T37CX7_bl.bam")
EML4_ALK_detection("YLRVNNYZ7D973YUL_bl.bam")
EML4_ALK_detection("MONA_40.bam")
EML4_ALK_detection("FDEDCZO3IR8TENC0_bl.bam")


EML4_sequence(EML4_ALK_detection("00QWTDYUH1E0VRM8_bl.bam"))
EML4_sequence(EML4_ALK_detection("9XPREVQOLXK3JE4S_bl.bam"))
EML4_sequence(EML4_ALK_detection("CQHQ4QA5K295LU8D_bl.bam"))
EML4_sequence(EML4_ALK_detection("Q54SLTX033G766IM_bl.bam"))
EML4_sequence(EML4_ALK_detection("4M0SDUZCZMWHIYJ7_bl.bam"))
EML4_sequence(EML4_ALK_detection("UE2R8PRMAT4T3IXD_bl.bam"))
EML4_sequence(EML4_ALK_detection("IT8BJVO03C08FV04_bl.bam"))
EML4_sequence(EML4_ALK_detection("YBNHFHWVB0HBC3YY_bl.bam"))
EML4_sequence(EML4_ALK_detection("4OOA9FR46IB4BXBJ_bl.bam"))
EML4_sequence(EML4_ALK_detection("G6M680NTHH1YGZ5A_bl.bam"))
EML4_sequence(EML4_ALK_detection("OUWIO70E08Q51YTB_bl.bam"))
EML4_sequence(EML4_ALK_detection("2UCZEDI4F35T6ILM_bl.bam"))
EML4_sequence(EML4_ALK_detection("PQ9NESTYL82NBF9B_bl.bam"))
EML4_sequence(EML4_ALK_detection("83Z7BF2N4Y12L933_bl.bam"))
EML4_sequence(EML4_ALK_detection("91R09H85UBLFEOLO_bl.bam"))
EML4_sequence(EML4_ALK_detection("K6YFO3FWXOFI99UZ_bl.bam"))
EML4_sequence(EML4_ALK_detection("E3ZSHQ5SSX9YNSUH_bl.bam"))
EML4_sequence(EML4_ALK_detection("YNKZ9UW1EMNM7TQ5_bl.bam"))
EML4_sequence(EML4_ALK_detection("5K04BRIUDO2EMCUM_bl.bam"))
EML4_sequence(EML4_ALK_detection("MJ0ZS032J5A67ZUA_bl.bam"))
EML4_sequence(EML4_ALK_detection("CMM8PC3S8M9NLOCH_bl.bam"))
EML4_sequence(EML4_ALK_detection("UT3Y7U411B7L6GU0_bl.bam"))
EML4_sequence(EML4_ALK_detection("B14Q10RS3BRU807A_bl.bam"))
EML4_sequence(EML4_ALK_detection("YBWTPETM88I7OL5N_bl.bam"))
EML4_sequence(EML4_ALK_detection("AEKYGMNC3109ZI9E_bl.bam"))
EML4_sequence(EML4_ALK_detection("MONA_26.bam"))
EML4_sequence(EML4_ALK_detection("SEAVIJ1HQS7PSXM1_bl.bam"))
EML4_sequence(EML4_ALK_detection("PH7LZCX099H0XGS6_bl.bam"))
EML4_sequence(EML4_ALK_detection("1POXVH7P4YZ0N22P_bl.bam"))
EML4_sequence(EML4_ALK_detection("885S9KA6LW9I28H9_bl.bam"))
EML4_sequence(EML4_ALK_detection("YZ0PPZ1A5JLCB27C_bl.bam"))
EML4_sequence(EML4_ALK_detection("MONA_32.bam"))
EML4_sequence(EML4_ALK_detection("MONA_33.bam"))
EML4_sequence(EML4_ALK_detection("72EP6S90YZWUFGRT_bl.bam"))
EML4_sequence(EML4_ALK_detection("6KYRWVT7W2KW1U48_bl.bam"))
EML4_sequence(EML4_ALK_detection("UOOXOPI9BOLDIU56_bl.bam"))
EML4_sequence(EML4_ALK_detection("40U550ULPLYA0U5D_bl.bam"))
EML4_sequence(EML4_ALK_detection("9Y6DEL9FY4T37CX7_bl.bam"))
EML4_sequence(EML4_ALK_detection("YLRVNNYZ7D973YUL_bl.bam"))
EML4_sequence(EML4_ALK_detection("MONA_40.bam"))
EML4_sequence(EML4_ALK_detection("FDEDCZO3IR8TENC0_bl.bam"))


ALK_sequence(EML4_ALK_detection("00QWTDYUH1E0VRM8_bl.bam"))
ALK_sequence(EML4_ALK_detection("9XPREVQOLXK3JE4S_bl.bam"))
ALK_sequence(EML4_ALK_detection("CQHQ4QA5K295LU8D_bl.bam"))
ALK_sequence(EML4_ALK_detection("Q54SLTX033G766IM_bl.bam"))
ALK_sequence(EML4_ALK_detection("4M0SDUZCZMWHIYJ7_bl.bam"))
ALK_sequence(EML4_ALK_detection("UE2R8PRMAT4T3IXD_bl.bam"))
ALK_sequence(EML4_ALK_detection("IT8BJVO03C08FV04_bl.bam"))
ALK_sequence(EML4_ALK_detection("YBNHFHWVB0HBC3YY_bl.bam"))
ALK_sequence(EML4_ALK_detection("4OOA9FR46IB4BXBJ_bl.bam"))
ALK_sequence(EML4_ALK_detection("G6M680NTHH1YGZ5A_bl.bam"))
ALK_sequence(EML4_ALK_detection("OUWIO70E08Q51YTB_bl.bam"))
ALK_sequence(EML4_ALK_detection("2UCZEDI4F35T6ILM_bl.bam"))
ALK_sequence(EML4_ALK_detection("PQ9NESTYL82NBF9B_bl.bam"))
ALK_sequence(EML4_ALK_detection("83Z7BF2N4Y12L933_bl.bam"))
ALK_sequence(EML4_ALK_detection("91R09H85UBLFEOLO_bl.bam"))
ALK_sequence(EML4_ALK_detection("K6YFO3FWXOFI99UZ_bl.bam"))
ALK_sequence(EML4_ALK_detection("E3ZSHQ5SSX9YNSUH_bl.bam"))
ALK_sequence(EML4_ALK_detection("YNKZ9UW1EMNM7TQ5_bl.bam"))
ALK_sequence(EML4_ALK_detection("5K04BRIUDO2EMCUM_bl.bam"))
ALK_sequence(EML4_ALK_detection("MJ0ZS032J5A67ZUA_bl.bam"))
ALK_sequence(EML4_ALK_detection("CMM8PC3S8M9NLOCH_bl.bam"))
ALK_sequence(EML4_ALK_detection("UT3Y7U411B7L6GU0_bl.bam"))
ALK_sequence(EML4_ALK_detection("B14Q10RS3BRU807A_bl.bam"))
ALK_sequence(EML4_ALK_detection("YBWTPETM88I7OL5N_bl.bam"))
ALK_sequence(EML4_ALK_detection("AEKYGMNC3109ZI9E_bl.bam"))
ALK_sequence(EML4_ALK_detection("MONA_26.bam"))
ALK_sequence(EML4_ALK_detection("SEAVIJ1HQS7PSXM1_bl.bam"))
ALK_sequence(EML4_ALK_detection("PH7LZCX099H0XGS6_bl.bam"))
ALK_sequence(EML4_ALK_detection("1POXVH7P4YZ0N22P_bl.bam"))
ALK_sequence(EML4_ALK_detection("885S9KA6LW9I28H9_bl.bam"))
ALK_sequence(EML4_ALK_detection("YZ0PPZ1A5JLCB27C_bl.bam"))
ALK_sequence(EML4_ALK_detection("MONA_32.bam"))
ALK_sequence(EML4_ALK_detection("MONA_33.bam"))
ALK_sequence(EML4_ALK_detection("72EP6S90YZWUFGRT_bl.bam"))
ALK_sequence(EML4_ALK_detection("6KYRWVT7W2KW1U48_bl.bam"))
ALK_sequence(EML4_ALK_detection("UOOXOPI9BOLDIU56_bl.bam"))
ALK_sequence(EML4_ALK_detection("40U550ULPLYA0U5D_bl.bam"))
ALK_sequence(EML4_ALK_detection("9Y6DEL9FY4T37CX7_bl.bam"))
ALK_sequence(EML4_ALK_detection("YLRVNNYZ7D973YUL_bl.bam"))
ALK_sequence(EML4_ALK_detection("MONA_40.bam"))
ALK_sequence(EML4_ALK_detection("FDEDCZO3IR8TENC0_bl.bam"))


break_position(EML4_ALK_detection("00QWTDYUH1E0VRM8_bl.bam"))
break_position(EML4_ALK_detection("9XPREVQOLXK3JE4S_bl.bam"))
break_position(EML4_ALK_detection("CQHQ4QA5K295LU8D_bl.bam"))
break_position(EML4_ALK_detection("Q54SLTX033G766IM_bl.bam"))
break_position(EML4_ALK_detection("4M0SDUZCZMWHIYJ7_bl.bam"))
break_position(EML4_ALK_detection("UE2R8PRMAT4T3IXD_bl.bam"))
break_position(EML4_ALK_detection("IT8BJVO03C08FV04_bl.bam"))
break_position(EML4_ALK_detection("YBNHFHWVB0HBC3YY_bl.bam"))
break_position(EML4_ALK_detection("4OOA9FR46IB4BXBJ_bl.bam"))
break_position(EML4_ALK_detection("G6M680NTHH1YGZ5A_bl.bam"))
break_position(EML4_ALK_detection("OUWIO70E08Q51YTB_bl.bam"))
break_position(EML4_ALK_detection("2UCZEDI4F35T6ILM_bl.bam"))
break_position(EML4_ALK_detection("PQ9NESTYL82NBF9B_bl.bam"))
break_position(EML4_ALK_detection("83Z7BF2N4Y12L933_bl.bam"))
break_position(EML4_ALK_detection("91R09H85UBLFEOLO_bl.bam"))
break_position(EML4_ALK_detection("K6YFO3FWXOFI99UZ_bl.bam"))
break_position(EML4_ALK_detection("E3ZSHQ5SSX9YNSUH_bl.bam"))
break_position(EML4_ALK_detection("YNKZ9UW1EMNM7TQ5_bl.bam"))
break_position(EML4_ALK_detection("5K04BRIUDO2EMCUM_bl.bam"))
break_position(EML4_ALK_detection("MJ0ZS032J5A67ZUA_bl.bam"))
break_position(EML4_ALK_detection("CMM8PC3S8M9NLOCH_bl.bam"))
break_position(EML4_ALK_detection("UT3Y7U411B7L6GU0_bl.bam"))
break_position(EML4_ALK_detection("B14Q10RS3BRU807A_bl.bam"))
break_position(EML4_ALK_detection("YBWTPETM88I7OL5N_bl.bam"))
break_position(EML4_ALK_detection("AEKYGMNC3109ZI9E_bl.bam"))
break_position(EML4_ALK_detection("MONA_26.bam"))
break_position(EML4_ALK_detection("SEAVIJ1HQS7PSXM1_bl.bam"))
break_position(EML4_ALK_detection("PH7LZCX099H0XGS6_bl.bam"))
break_position(EML4_ALK_detection("1POXVH7P4YZ0N22P_bl.bam"))
break_position(EML4_ALK_detection("885S9KA6LW9I28H9_bl.bam"))
break_position(EML4_ALK_detection("YZ0PPZ1A5JLCB27C_bl.bam"))
break_position(EML4_ALK_detection("MONA_32.bam"))
break_position(EML4_ALK_detection("MONA_33.bam"))
break_position(EML4_ALK_detection("72EP6S90YZWUFGRT_bl.bam"))
break_position(EML4_ALK_detection("6KYRWVT7W2KW1U48_bl.bam"))
break_position(EML4_ALK_detection("UOOXOPI9BOLDIU56_bl.bam"))
break_position(EML4_ALK_detection("40U550ULPLYA0U5D_bl.bam"))
break_position(EML4_ALK_detection("9Y6DEL9FY4T37CX7_bl.bam"))
break_position(EML4_ALK_detection("YLRVNNYZ7D973YUL_bl.bam"))
break_position(EML4_ALK_detection("MONA_40.bam"))
break_position(EML4_ALK_detection("FDEDCZO3IR8TENC0_bl.bam"))


break_position_depth("00QWTDYUH1E0VRM8_bl.bam", EML4_ALK_detection("00QWTDYUH1E0VRM8_bl.bam"))
break_position_depth("9XPREVQOLXK3JE4S_bl.bam", EML4_ALK_detection("9XPREVQOLXK3JE4S_bl.bam"))
break_position_depth("CQHQ4QA5K295LU8D_bl.bam", EML4_ALK_detection("CQHQ4QA5K295LU8D_bl.bam"))
break_position_depth("Q54SLTX033G766IM_bl.bam", EML4_ALK_detection("Q54SLTX033G766IM_bl.bam"))
break_position_depth("4M0SDUZCZMWHIYJ7_bl.bam", EML4_ALK_detection("4M0SDUZCZMWHIYJ7_bl.bam"))
break_position_depth("UE2R8PRMAT4T3IXD_bl.bam", EML4_ALK_detection("UE2R8PRMAT4T3IXD_bl.bam"))
break_position_depth("IT8BJVO03C08FV04_bl.bam", EML4_ALK_detection("IT8BJVO03C08FV04_bl.bam"))
break_position_depth("YBNHFHWVB0HBC3YY_bl.bam", EML4_ALK_detection("YBNHFHWVB0HBC3YY_bl.bam"))
break_position_depth("4OOA9FR46IB4BXBJ_bl.bam", EML4_ALK_detection("4OOA9FR46IB4BXBJ_bl.bam"))
break_position_depth("G6M680NTHH1YGZ5A_bl.bam", EML4_ALK_detection("G6M680NTHH1YGZ5A_bl.bam"))
break_position_depth("OUWIO70E08Q51YTB_bl.bam", EML4_ALK_detection("OUWIO70E08Q51YTB_bl.bam"))
break_position_depth("2UCZEDI4F35T6ILM_bl.bam", EML4_ALK_detection("2UCZEDI4F35T6ILM_bl.bam"))
break_position_depth("PQ9NESTYL82NBF9B_bl.bam", EML4_ALK_detection("PQ9NESTYL82NBF9B_bl.bam"))
break_position_depth("83Z7BF2N4Y12L933_bl.bam", EML4_ALK_detection("83Z7BF2N4Y12L933_bl.bam"))
break_position_depth("91R09H85UBLFEOLO_bl.bam", EML4_ALK_detection("91R09H85UBLFEOLO_bl.bam"))
break_position_depth("K6YFO3FWXOFI99UZ_bl.bam", EML4_ALK_detection("K6YFO3FWXOFI99UZ_bl.bam"))
break_position_depth("E3ZSHQ5SSX9YNSUH_bl.bam", EML4_ALK_detection("E3ZSHQ5SSX9YNSUH_bl.bam"))
break_position_depth("YNKZ9UW1EMNM7TQ5_bl.bam", EML4_ALK_detection("YNKZ9UW1EMNM7TQ5_bl.bam"))
break_position_depth("5K04BRIUDO2EMCUM_bl.bam", EML4_ALK_detection("5K04BRIUDO2EMCUM_bl.bam"))
break_position_depth("MJ0ZS032J5A67ZUA_bl.bam", EML4_ALK_detection("MJ0ZS032J5A67ZUA_bl.bam"))
break_position_depth("CMM8PC3S8M9NLOCH_bl.bam", EML4_ALK_detection("CMM8PC3S8M9NLOCH_bl.bam"))
break_position_depth("UT3Y7U411B7L6GU0_bl.bam", EML4_ALK_detection("UT3Y7U411B7L6GU0_bl.bam"))
break_position_depth("B14Q10RS3BRU807A_bl.bam", EML4_ALK_detection("B14Q10RS3BRU807A_bl.bam"))
break_position_depth("YBWTPETM88I7OL5N_bl.bam", EML4_ALK_detection("YBWTPETM88I7OL5N_bl.bam"))
break_position_depth("AEKYGMNC3109ZI9E_bl.bam", EML4_ALK_detection("AEKYGMNC3109ZI9E_bl.bam"))
break_position_depth("MONA_26.bam", EML4_ALK_detection("MONA_26.bam"))
break_position_depth("SEAVIJ1HQS7PSXM1_bl.bam", EML4_ALK_detection("SEAVIJ1HQS7PSXM1_bl.bam"))
break_position_depth("PH7LZCX099H0XGS6_bl.bam", EML4_ALK_detection("PH7LZCX099H0XGS6_bl.bam"))
break_position_depth("1POXVH7P4YZ0N22P_bl.bam", EML4_ALK_detection("1POXVH7P4YZ0N22P_bl.bam"))
break_position_depth("885S9KA6LW9I28H9_bl.bam", EML4_ALK_detection("885S9KA6LW9I28H9_bl.bam"))
break_position_depth("YZ0PPZ1A5JLCB27C_bl.bam", EML4_ALK_detection("YZ0PPZ1A5JLCB27C_bl.bam"))
break_position_depth("MONA_32.bam", EML4_ALK_detection("MONA_32.bam"))
break_position_depth("MONA_33.bam", EML4_ALK_detection("MONA_33.bam"))
break_position_depth("72EP6S90YZWUFGRT_bl.bam", EML4_ALK_detection("72EP6S90YZWUFGRT_bl.bam"))
break_position_depth("6KYRWVT7W2KW1U48_bl.bam", EML4_ALK_detection("6KYRWVT7W2KW1U48_bl.bam"))
break_position_depth("UOOXOPI9BOLDIU56_bl.bam", EML4_ALK_detection("UOOXOPI9BOLDIU56_bl.bam"))
break_position_depth("40U550ULPLYA0U5D_bl.bam", EML4_ALK_detection("40U550ULPLYA0U5D_bl.bam"))
break_position_depth("9Y6DEL9FY4T37CX7_bl.bam", EML4_ALK_detection("9Y6DEL9FY4T37CX7_bl.bam"))
break_position_depth("YLRVNNYZ7D973YUL_bl.bam", EML4_ALK_detection("YLRVNNYZ7D973YUL_bl.bam"))
break_position_depth("MONA_40.bam", EML4_ALK_detection("MONA_40.bam"))
break_position_depth("FDEDCZO3IR8TENC0_bl.bam", EML4_ALK_detection("FDEDCZO3IR8TENC0_bl.bam"))


EML4_ALK_analysis("00QWTDYUH1E0VRM8_bl.bam")
EML4_ALK_analysis("9XPREVQOLXK3JE4S_bl.bam")
EML4_ALK_analysis("CQHQ4QA5K295LU8D_bl.bam")
EML4_ALK_analysis("Q54SLTX033G766IM_bl.bam")
EML4_ALK_analysis("4M0SDUZCZMWHIYJ7_bl.bam")
EML4_ALK_analysis("UE2R8PRMAT4T3IXD_bl.bam")
EML4_ALK_analysis("IT8BJVO03C08FV04_bl.bam")
EML4_ALK_analysis("YBNHFHWVB0HBC3YY_bl.bam")
EML4_ALK_analysis("4OOA9FR46IB4BXBJ_bl.bam")
EML4_ALK_analysis("G6M680NTHH1YGZ5A_bl.bam")
EML4_ALK_analysis("OUWIO70E08Q51YTB_bl.bam")
EML4_ALK_analysis("2UCZEDI4F35T6ILM_bl.bam")
EML4_ALK_analysis("PQ9NESTYL82NBF9B_bl.bam")
EML4_ALK_analysis("83Z7BF2N4Y12L933_bl.bam")
EML4_ALK_analysis("91R09H85UBLFEOLO_bl.bam")
EML4_ALK_analysis("K6YFO3FWXOFI99UZ_bl.bam")
EML4_ALK_analysis("E3ZSHQ5SSX9YNSUH_bl.bam")
EML4_ALK_analysis("YNKZ9UW1EMNM7TQ5_bl.bam")
EML4_ALK_analysis("5K04BRIUDO2EMCUM_bl.bam")
EML4_ALK_analysis("MJ0ZS032J5A67ZUA_bl.bam")
EML4_ALK_analysis("CMM8PC3S8M9NLOCH_bl.bam")
EML4_ALK_analysis("UT3Y7U411B7L6GU0_bl.bam")
EML4_ALK_analysis("B14Q10RS3BRU807A_bl.bam")
EML4_ALK_analysis("YBWTPETM88I7OL5N_bl.bam")
EML4_ALK_analysis("AEKYGMNC3109ZI9E_bl.bam")
EML4_ALK_analysis("MONA_26.bam")
EML4_ALK_analysis("SEAVIJ1HQS7PSXM1_bl.bam")
EML4_ALK_analysis("PH7LZCX099H0XGS6_bl.bam")
EML4_ALK_analysis("1POXVH7P4YZ0N22P_bl.bam")
EML4_ALK_analysis("885S9KA6LW9I28H9_bl.bam")
EML4_ALK_analysis("YZ0PPZ1A5JLCB27C_bl.bam")
EML4_ALK_analysis("MONA_32.bam")
EML4_ALK_analysis("MONA_33.bam")
EML4_ALK_analysis("72EP6S90YZWUFGRT_bl.bam")
EML4_ALK_analysis("6KYRWVT7W2KW1U48_bl.bam")
EML4_ALK_analysis("UOOXOPI9BOLDIU56_bl.bam")
EML4_ALK_analysis("40U550ULPLYA0U5D_bl.bam")
EML4_ALK_analysis("9Y6DEL9FY4T37CX7_bl.bam")
EML4_ALK_analysis("YLRVNNYZ7D973YUL_bl.bam")
EML4_ALK_analysis("MONA_40.bam")
EML4_ALK_analysis("FDEDCZO3IR8TENC0_bl.bam")

####Cells####
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Cells/BAM")
EML4_ALK_detection("PosDeduped-HCC827.bam")
EML4_ALK_detection("PosDeduped-A549.bam")
H2228_res <- EML4_ALK_detection("PosDeduped-H2228.bam")
H3122_res <- EML4_ALK_detection("PosDeduped-H3122.bam")

EML4_sequence(EML4_ALK_detection("PosDeduped-HCC827.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-A549.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-H2228.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-H3122.bam"))

ALK_sequence(EML4_ALK_detection("PosDeduped-HCC827.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-A549.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-H2228.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-H3122.bam"))

break_position(EML4_ALK_detection("PosDeduped-HCC827.bam"))
break_position(EML4_ALK_detection("PosDeduped-A549.bam"))
break_position(EML4_ALK_detection("PosDeduped-H2228.bam"))
break_position(EML4_ALK_detection("PosDeduped-H3122.bam"))

break_position_depth("PosDeduped-HCC827.bam", EML4_ALK_detection("PosDeduped-HCC827.bam"))
break_position_depth("PosDeduped-A549.bam", EML4_ALK_detection("PosDeduped-A549.bam"))
break_position_depth("PosDeduped-H2228.bam", EML4_ALK_detection("PosDeduped-H2228.bam"))
break_position_depth("PosDeduped-H3122.bam", EML4_ALK_detection("PosDeduped-H3122.bam"))

EML4_ALK_analysis("PosDeduped-HCC827.bam")
EML4_ALK_analysis("PosDeduped-A549.bam")
EML4_ALK_analysis("PosDeduped-H2228.bam")
EML4_ALK_analysis("PosDeduped-H3122.bam")

####Controls####
setwd("C:/Users/Christoffer/OneDrive/1PhD/Fragmentering/PosDeduped files")
EML4_ALK_detection("PosDeduped-rask_kontrol_1_input.bam")
EML4_ALK_detection("PosDeduped-rask_kontrol_2_input.bam")
EML4_ALK_detection("PosDeduped-rask_kontrol_3_input.bam")
EML4_ALK_detection("PosDeduped-rask_kontrol_4_input.bam")
EML4_ALK_detection("PosDeduped-rask_kontrol_5_input.bam")
EML4_ALK_detection("PosDeduped-rask_kontrol_6_input.bam")
EML4_ALK_detection("PosDeduped-rask_kontrol_7_input.bam")

EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_1_input.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_2_input.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_3_input.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_4_input.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_5_input.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_6_input.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_7_input.bam"))

ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_1_input.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_2_input.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_3_input.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_4_input.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_5_input.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_6_input.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-rask_kontrol_7_input.bam"))

break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_1_input.bam"))
break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_2_input.bam"))
break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_3_input.bam"))
break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_4_input.bam"))
break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_5_input.bam"))
break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_6_input.bam"))
break_position(EML4_ALK_detection("PosDeduped-rask_kontrol_7_input.bam"))

break_position_depth("PosDeduped-rask_kontrol_1_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_1_input.bam"))
break_position_depth("PosDeduped-rask_kontrol_2_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_2_input.bam"))
break_position_depth("PosDeduped-rask_kontrol_3_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_3_input.bam"))
break_position_depth("PosDeduped-rask_kontrol_4_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_4_input.bam"))
break_position_depth("PosDeduped-rask_kontrol_5_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_5_input.bam"))
break_position_depth("PosDeduped-rask_kontrol_6_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_6_input.bam"))
break_position_depth("PosDeduped-rask_kontrol_7_input.bam", EML4_ALK_detection("PosDeduped-rask_kontrol_7_input.bam"))

EML4_ALK_analysis("PosDeduped-rask_kontrol_1_input.bam")
EML4_ALK_analysis("PosDeduped-rask_kontrol_2_input.bam")
EML4_ALK_analysis("PosDeduped-rask_kontrol_3_input.bam")
EML4_ALK_analysis("PosDeduped-rask_kontrol_4_input.bam")
EML4_ALK_analysis("PosDeduped-rask_kontrol_5_input.bam")
EML4_ALK_analysis("PosDeduped-rask_kontrol_6_input.bam")
EML4_ALK_analysis("PosDeduped-rask_kontrol_7_input.bam")


####Validation####
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Validation cohort")
EML4_ALK_detection("PosDeduped-val01.bam")
EML4_ALK_detection("PosDeduped-val02.bam")
EML4_ALK_detection("PosDeduped-val03.bam")
EML4_ALK_detection("PosDeduped-val04.bam")
EML4_ALK_detection("PosDeduped-val05.bam")
EML4_ALK_detection("PosDeduped-val06.bam")
EML4_ALK_detection("PosDeduped-val07.bam")
EML4_ALK_detection("PosDeduped-val08.bam")
EML4_ALK_detection("PosDeduped-val09.bam")
EML4_ALK_detection("PosDeduped-val10.bam")
EML4_ALK_detection("PosDeduped-val11.bam")
EML4_ALK_detection("PosDeduped-val12.bam")
EML4_ALK_detection("PosDeduped-val13.bam")
EML4_ALK_detection("PosDeduped-val14.bam")
EML4_ALK_detection("PosDeduped-val15.bam")
EML4_ALK_detection("PosDeduped-val16.bam")
EML4_ALK_detection("PosDeduped-val17.bam")
EML4_ALK_detection("PosDeduped-val18.bam")
EML4_ALK_detection("PosDeduped-val19.bam")
EML4_ALK_detection("PosDeduped-val20.bam")
EML4_ALK_detection("PosDeduped-val21.bam")
EML4_ALK_detection("PosDeduped-val22.bam")
EML4_ALK_detection("PosDeduped-val23.bam")
EML4_ALK_detection("PosDeduped-val24.bam")
EML4_ALK_detection("PosDeduped-val25.bam")
EML4_ALK_detection("PosDeduped-val26.bam")
EML4_ALK_detection("PosDeduped-val27.bam")
EML4_ALK_detection("PosDeduped-val28.bam")
EML4_ALK_detection("PosDeduped-val29.bam")
EML4_ALK_detection("PosDeduped-val30.bam")
EML4_ALK_detection("PosDeduped-val31.bam")
EML4_ALK_detection("PosDeduped-val32.bam")
EML4_ALK_detection("PosDeduped-val33.bam")
EML4_ALK_detection("PosDeduped-val34.bam")
EML4_ALK_detection("PosDeduped-val35.bam")
EML4_ALK_detection("PosDeduped-val36.bam")
EML4_ALK_detection("PosDeduped-val37.bam")
EML4_ALK_detection("PosDeduped-val38.bam")
EML4_ALK_detection("PosDeduped-val39.bam")
EML4_ALK_detection("PosDeduped-val40.bam")
EML4_ALK_detection("PosDeduped-val41.bam")
EML4_ALK_detection("PosDeduped-val42.bam")
EML4_ALK_detection("PosDeduped-val43.bam")
EML4_ALK_detection("PosDeduped-val44.bam")
EML4_ALK_detection("PosDeduped-val45.bam")
EML4_ALK_detection("PosDeduped-val46.bam")
EML4_ALK_detection("PosDeduped-val47.bam")
EML4_ALK_detection("PosDeduped-val48.bam")


EML4_sequence(EML4_ALK_detection("PosDeduped-val01.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val02.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val03.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val04.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val05.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val06.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val07.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val08.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val09.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val10.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val11.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val12.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val13.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val14.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val15.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val16.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val17.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val18.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val19.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val20.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val21.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val22.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val23.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val24.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val25.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val26.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val27.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val28.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val29.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val30.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val31.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val32.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val33.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val34.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val35.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val36.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val37.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val38.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val39.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val40.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val41.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val42.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val43.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val44.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val45.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val46.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val47.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val48.bam"))


ALK_sequence(EML4_ALK_detection("PosDeduped-val01.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val02.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val03.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val04.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val05.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val06.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val07.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val08.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val09.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val10.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val11.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val12.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val13.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val14.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val15.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val16.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val17.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val18.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val19.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val20.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val21.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val22.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val23.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val24.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val25.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val26.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val27.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val28.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val29.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val30.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val31.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val32.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val33.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val34.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val35.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val36.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val37.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val38.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val39.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val40.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val41.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val42.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val43.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val44.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val45.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val46.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val47.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val48.bam"))


break_position(EML4_ALK_detection("PosDeduped-val01.bam"))
break_position(EML4_ALK_detection("PosDeduped-val02.bam"))
break_position(EML4_ALK_detection("PosDeduped-val03.bam"))
break_position(EML4_ALK_detection("PosDeduped-val04.bam"))
break_position(EML4_ALK_detection("PosDeduped-val05.bam"))
break_position(EML4_ALK_detection("PosDeduped-val06.bam"))
break_position(EML4_ALK_detection("PosDeduped-val07.bam"))
break_position(EML4_ALK_detection("PosDeduped-val08.bam"))
break_position(EML4_ALK_detection("PosDeduped-val09.bam"))
break_position(EML4_ALK_detection("PosDeduped-val10.bam"))
break_position(EML4_ALK_detection("PosDeduped-val11.bam"))
break_position(EML4_ALK_detection("PosDeduped-val12.bam"))
break_position(EML4_ALK_detection("PosDeduped-val13.bam"))
break_position(EML4_ALK_detection("PosDeduped-val14.bam"))
break_position(EML4_ALK_detection("PosDeduped-val15.bam"))
break_position(EML4_ALK_detection("PosDeduped-val16.bam"))
break_position(EML4_ALK_detection("PosDeduped-val17.bam"))
break_position(EML4_ALK_detection("PosDeduped-val18.bam"))
break_position(EML4_ALK_detection("PosDeduped-val19.bam"))
break_position(EML4_ALK_detection("PosDeduped-val20.bam"))
break_position(EML4_ALK_detection("PosDeduped-val21.bam"))
break_position(EML4_ALK_detection("PosDeduped-val22.bam"))
break_position(EML4_ALK_detection("PosDeduped-val23.bam"))
break_position(EML4_ALK_detection("PosDeduped-val24.bam"))
break_position(EML4_ALK_detection("PosDeduped-val25.bam"))
break_position(EML4_ALK_detection("PosDeduped-val26.bam"))
break_position(EML4_ALK_detection("PosDeduped-val27.bam"))
break_position(EML4_ALK_detection("PosDeduped-val28.bam"))
break_position(EML4_ALK_detection("PosDeduped-val29.bam"))
break_position(EML4_ALK_detection("PosDeduped-val30.bam"))
break_position(EML4_ALK_detection("PosDeduped-val31.bam"))
break_position(EML4_ALK_detection("PosDeduped-val32.bam"))
break_position(EML4_ALK_detection("PosDeduped-val33.bam"))
break_position(EML4_ALK_detection("PosDeduped-val34.bam"))
break_position(EML4_ALK_detection("PosDeduped-val35.bam"))
break_position(EML4_ALK_detection("PosDeduped-val36.bam"))
break_position(EML4_ALK_detection("PosDeduped-val37.bam"))
break_position(EML4_ALK_detection("PosDeduped-val38.bam"))
break_position(EML4_ALK_detection("PosDeduped-val39.bam"))
break_position(EML4_ALK_detection("PosDeduped-val40.bam"))
break_position(EML4_ALK_detection("PosDeduped-val41.bam"))
break_position(EML4_ALK_detection("PosDeduped-val42.bam"))
break_position(EML4_ALK_detection("PosDeduped-val43.bam"))
break_position(EML4_ALK_detection("PosDeduped-val44.bam"))
break_position(EML4_ALK_detection("PosDeduped-val45.bam"))
break_position(EML4_ALK_detection("PosDeduped-val46.bam"))
break_position(EML4_ALK_detection("PosDeduped-val47.bam"))
break_position(EML4_ALK_detection("PosDeduped-val48.bam"))


break_position_depth("PosDeduped-val01.bam", EML4_ALK_detection("PosDeduped-val01.bam"))
break_position_depth("PosDeduped-val02.bam", EML4_ALK_detection("PosDeduped-val02.bam"))
break_position_depth("PosDeduped-val03.bam", EML4_ALK_detection("PosDeduped-val03.bam"))
break_position_depth("PosDeduped-val04.bam", EML4_ALK_detection("PosDeduped-val04.bam"))
break_position_depth("PosDeduped-val05.bam", EML4_ALK_detection("PosDeduped-val05.bam"))
break_position_depth("PosDeduped-val06.bam", EML4_ALK_detection("PosDeduped-val06.bam"))
break_position_depth("PosDeduped-val07.bam", EML4_ALK_detection("PosDeduped-val07.bam"))
break_position_depth("PosDeduped-val08.bam", EML4_ALK_detection("PosDeduped-val08.bam"))
break_position_depth("PosDeduped-val09.bam", EML4_ALK_detection("PosDeduped-val09.bam"))
break_position_depth("PosDeduped-val10.bam", EML4_ALK_detection("PosDeduped-val10.bam"))
break_position_depth("PosDeduped-val11.bam", EML4_ALK_detection("PosDeduped-val11.bam"))
break_position_depth("PosDeduped-val12.bam", EML4_ALK_detection("PosDeduped-val12.bam"))
break_position_depth("PosDeduped-val13.bam", EML4_ALK_detection("PosDeduped-val13.bam"))
break_position_depth("PosDeduped-val14.bam", EML4_ALK_detection("PosDeduped-val14.bam"))
break_position_depth("PosDeduped-val15.bam", EML4_ALK_detection("PosDeduped-val15.bam"))
break_position_depth("PosDeduped-val16.bam", EML4_ALK_detection("PosDeduped-val16.bam"))
break_position_depth("PosDeduped-val17.bam", EML4_ALK_detection("PosDeduped-val17.bam"))
break_position_depth("PosDeduped-val18.bam", EML4_ALK_detection("PosDeduped-val18.bam"))
break_position_depth("PosDeduped-val19.bam", EML4_ALK_detection("PosDeduped-val19.bam"))
break_position_depth("PosDeduped-val20.bam", EML4_ALK_detection("PosDeduped-val20.bam"))
break_position_depth("PosDeduped-val21.bam", EML4_ALK_detection("PosDeduped-val21.bam"))
break_position_depth("PosDeduped-val22.bam", EML4_ALK_detection("PosDeduped-val22.bam"))
break_position_depth("PosDeduped-val23.bam", EML4_ALK_detection("PosDeduped-val23.bam"))
break_position_depth("PosDeduped-val24.bam", EML4_ALK_detection("PosDeduped-val24.bam"))
break_position_depth("PosDeduped-val25.bam", EML4_ALK_detection("PosDeduped-val25.bam"))
break_position_depth("PosDeduped-val26.bam", EML4_ALK_detection("PosDeduped-val26.bam"))
break_position_depth("PosDeduped-val27.bam", EML4_ALK_detection("PosDeduped-val27.bam"))
break_position_depth("PosDeduped-val28.bam", EML4_ALK_detection("PosDeduped-val28.bam"))
break_position_depth("PosDeduped-val29.bam", EML4_ALK_detection("PosDeduped-val29.bam"))
break_position_depth("PosDeduped-val30.bam", EML4_ALK_detection("PosDeduped-val30.bam"))
break_position_depth("PosDeduped-val31.bam", EML4_ALK_detection("PosDeduped-val31.bam"))
break_position_depth("PosDeduped-val32.bam", EML4_ALK_detection("PosDeduped-val32.bam"))
break_position_depth("PosDeduped-val33.bam", EML4_ALK_detection("PosDeduped-val33.bam"))
break_position_depth("PosDeduped-val34.bam", EML4_ALK_detection("PosDeduped-val34.bam"))
break_position_depth("PosDeduped-val35.bam", EML4_ALK_detection("PosDeduped-val35.bam"))
break_position_depth("PosDeduped-val36.bam", EML4_ALK_detection("PosDeduped-val36.bam"))
break_position_depth("PosDeduped-val37.bam", EML4_ALK_detection("PosDeduped-val37.bam"))
break_position_depth("PosDeduped-val38.bam", EML4_ALK_detection("PosDeduped-val38.bam"))
break_position_depth("PosDeduped-val39.bam", EML4_ALK_detection("PosDeduped-val39.bam"))
break_position_depth("PosDeduped-val40.bam", EML4_ALK_detection("PosDeduped-val40.bam"))
break_position_depth("PosDeduped-val41.bam", EML4_ALK_detection("PosDeduped-val41.bam"))
break_position_depth("PosDeduped-val42.bam", EML4_ALK_detection("PosDeduped-val42.bam"))
break_position_depth("PosDeduped-val43.bam", EML4_ALK_detection("PosDeduped-val43.bam"))
break_position_depth("PosDeduped-val44.bam", EML4_ALK_detection("PosDeduped-val44.bam"))
break_position_depth("PosDeduped-val45.bam", EML4_ALK_detection("PosDeduped-val45.bam"))
break_position_depth("PosDeduped-val46.bam", EML4_ALK_detection("PosDeduped-val46.bam"))
break_position_depth("PosDeduped-val47.bam", EML4_ALK_detection("PosDeduped-val47.bam"))
break_position_depth("PosDeduped-val48.bam", EML4_ALK_detection("PosDeduped-val48.bam"))


EML4_ALK_analysis("PosDeduped-val01.bam")
EML4_ALK_analysis("PosDeduped-val02.bam")
EML4_ALK_analysis("PosDeduped-val03.bam")
EML4_ALK_analysis("PosDeduped-val04.bam")
EML4_ALK_analysis("PosDeduped-val05.bam")
EML4_ALK_analysis("PosDeduped-val06.bam")
EML4_ALK_analysis("PosDeduped-val07.bam")
EML4_ALK_analysis("PosDeduped-val08.bam")
EML4_ALK_analysis("PosDeduped-val09.bam")
EML4_ALK_analysis("PosDeduped-val10.bam")
EML4_ALK_analysis("PosDeduped-val11.bam")
EML4_ALK_analysis("PosDeduped-val12.bam")
EML4_ALK_analysis("PosDeduped-val13.bam")
EML4_ALK_analysis("PosDeduped-val14.bam")
EML4_ALK_analysis("PosDeduped-val15.bam")
EML4_ALK_analysis("PosDeduped-val16.bam")
EML4_ALK_analysis("PosDeduped-val17.bam")
EML4_ALK_analysis("PosDeduped-val18.bam")
EML4_ALK_analysis("PosDeduped-val19.bam")
EML4_ALK_analysis("PosDeduped-val20.bam")
EML4_ALK_analysis("PosDeduped-val21.bam")
EML4_ALK_analysis("PosDeduped-val22.bam")
EML4_ALK_analysis("PosDeduped-val23.bam")
EML4_ALK_analysis("PosDeduped-val24.bam")
EML4_ALK_analysis("PosDeduped-val25.bam")
EML4_ALK_analysis("PosDeduped-val26.bam")
EML4_ALK_analysis("PosDeduped-val27.bam")
EML4_ALK_analysis("PosDeduped-val28.bam")
EML4_ALK_analysis("PosDeduped-val29.bam")
EML4_ALK_analysis("PosDeduped-val30.bam")
EML4_ALK_analysis("PosDeduped-val31.bam")
EML4_ALK_analysis("PosDeduped-val32.bam")
EML4_ALK_analysis("PosDeduped-val33.bam")
EML4_ALK_analysis("PosDeduped-val34.bam")
EML4_ALK_analysis("PosDeduped-val35.bam")
EML4_ALK_analysis("PosDeduped-val36.bam")
EML4_ALK_analysis("PosDeduped-val37.bam")
EML4_ALK_analysis("PosDeduped-val38.bam")
EML4_ALK_analysis("PosDeduped-val39.bam")
EML4_ALK_analysis("PosDeduped-val40.bam")
EML4_ALK_analysis("PosDeduped-val41.bam")
EML4_ALK_analysis("PosDeduped-val42.bam")
EML4_ALK_analysis("PosDeduped-val43.bam")
EML4_ALK_analysis("PosDeduped-val44.bam")
EML4_ALK_analysis("PosDeduped-val45.bam")
EML4_ALK_analysis("PosDeduped-val46.bam")
EML4_ALK_analysis("PosDeduped-val47.bam")
EML4_ALK_analysis("PosDeduped-val48.bam")

####Patient 3 and 9#####
library(DNAfusion)
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Validation cohort")
EML4_ALK_analysis("PosDeduped-val26.bam")
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Patient_3_and_9")
EML4_ALK_analysis("PosDeduped-4005-2.bam")
EML4_ALK_analysis("PosDeduped-4005-3.bam")
EML4_ALK_analysis("PosDeduped-4005-14.bam")

setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Validation cohort")
EML4_ALK_analysis("PosDeduped-val10.bam")
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Patient_3_and_9")
EML4_ALK_analysis("PosDeduped-4009-2.bam")
EML4_ALK_detection("PosDeduped-4009-3.bam")
EML4_ALK_analysis("PosDeduped-4009-14.bam")
####runtime####
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK patienter/Maiken cohort/PosDeduped")
files <- c("00QWTDYUH1E0VRM8_bl.bam",
           "9XPREVQOLXK3JE4S_bl.bam",
           "CQHQ4QA5K295LU8D_bl.bam",
           "Q54SLTX033G766IM_bl.bam",
           "4M0SDUZCZMWHIYJ7_bl.bam",
           "UE2R8PRMAT4T3IXD_bl.bam",
           "IT8BJVO03C08FV04_bl.bam",
           "YBNHFHWVB0HBC3YY_bl.bam",
           "4OOA9FR46IB4BXBJ_bl.bam",
           "G6M680NTHH1YGZ5A_bl.bam",
           "OUWIO70E08Q51YTB_bl.bam",
           "2UCZEDI4F35T6ILM_bl.bam",
           "PQ9NESTYL82NBF9B_bl.bam",
           "83Z7BF2N4Y12L933_bl.bam",
           "91R09H85UBLFEOLO_bl.bam",
           "K6YFO3FWXOFI99UZ_bl.bam",
           "E3ZSHQ5SSX9YNSUH_bl.bam",
           "YNKZ9UW1EMNM7TQ5_bl.bam",
           "5K04BRIUDO2EMCUM_bl.bam",
           "MJ0ZS032J5A67ZUA_bl.bam",
           "CMM8PC3S8M9NLOCH_bl.bam",
           "UT3Y7U411B7L6GU0_bl.bam",
           "B14Q10RS3BRU807A_bl.bam",
           "YBWTPETM88I7OL5N_bl.bam",
           "AEKYGMNC3109ZI9E_bl.bam",
           "MONA_26.bam",
           "SEAVIJ1HQS7PSXM1_bl.bam",
           "PH7LZCX099H0XGS6_bl.bam",
           "1POXVH7P4YZ0N22P_bl.bam",
           "885S9KA6LW9I28H9_bl.bam",
           "YZ0PPZ1A5JLCB27C_bl.bam",
           "MONA_32.bam",
           "MONA_33.bam",
           "72EP6S90YZWUFGRT_bl.bam",
           "6KYRWVT7W2KW1U48_bl.bam",
           "UOOXOPI9BOLDIU56_bl.bam",
           "40U550ULPLYA0U5D_bl.bam",
           "9Y6DEL9FY4T37CX7_bl.bam",
           "YLRVNNYZ7D973YUL_bl.bam",
           "MONA_40.bam",
           "FDEDCZO3IR8TENC0_bl.bam")

library(DNAfusion)
runtimeFunction <- function(vec){
    times <- c()
    for (i in 1:length(vec)){
        if(i != 17){
            start.time <- Sys.time()
            EML4_ALK_analysis(vec[i])
            end.time <- Sys.time()
            time.taken <- end.time - start.time
            times[i] <- time.taken
            print(i)
        }

    }
    return(times)
}
runtimeFunction(files)

