setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Cells/BAM")
EML4_ALK_analysis("PosDeduped-HCC827.bam")
EML4_ALK_analysis("PosDeduped-A549.bam")
EML4_ALK_analysis("PosDeduped-H2228.bam")
EML4_ALK_analysis("PosDeduped-H3122.bam")
library(DNAfusion)
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Maiken cohort/PosDeduped")
MonAlec_detection <- microbenchmark::microbenchmark(EML4_ALK_detection("00QWTDYUH1E0VRM8_bl.bam"),
                               EML4_ALK_detection("9XPREVQOLXK3JE4S_bl.bam"),
                               EML4_ALK_detection("CQHQ4QA5K295LU8D_bl.bam"),
                               EML4_ALK_detection("Q54SLTX033G766IM_bl.bam"),
                               EML4_ALK_detection("4M0SDUZCZMWHIYJ7_bl.bam"),
                               EML4_ALK_detection("UE2R8PRMAT4T3IXD_bl.bam"),
                               EML4_ALK_detection("IT8BJVO03C08FV04_bl.bam"),
                               EML4_ALK_detection("YBNHFHWVB0HBC3YY_bl.bam"),
                               EML4_ALK_detection("4OOA9FR46IB4BXBJ_bl.bam"),
                               EML4_ALK_detection("G6M680NTHH1YGZ5A_bl.bam"),
                               EML4_ALK_detection("OUWIO70E08Q51YTB_bl.bam"),
                               EML4_ALK_detection("2UCZEDI4F35T6ILM_bl.bam"),
                               EML4_ALK_detection("PQ9NESTYL82NBF9B_bl.bam"),
                               EML4_ALK_detection("83Z7BF2N4Y12L933_bl.bam"),
                               EML4_ALK_detection("91R09H85UBLFEOLO_bl.bam"),
                               EML4_ALK_detection("K6YFO3FWXOFI99UZ_bl.bam"),
                               EML4_ALK_detection("E3ZSHQ5SSX9YNSUH_bl.bam"),
                               EML4_ALK_detection("YNKZ9UW1EMNM7TQ5_bl.bam"),
                               EML4_ALK_detection("5K04BRIUDO2EMCUM_bl.bam"),
                               EML4_ALK_detection("MJ0ZS032J5A67ZUA_bl.bam"),
                               EML4_ALK_detection("CMM8PC3S8M9NLOCH_bl.bam"),
                               EML4_ALK_detection("UT3Y7U411B7L6GU0_bl.bam"),
                               EML4_ALK_detection("B14Q10RS3BRU807A_bl.bam"),
                               EML4_ALK_detection("YBWTPETM88I7OL5N_bl.bam"),
                               EML4_ALK_detection("AEKYGMNC3109ZI9E_bl.bam"),
                               EML4_ALK_detection("MONA_26.bam"),
                               EML4_ALK_detection("SEAVIJ1HQS7PSXM1_bl.bam"),
                               EML4_ALK_detection("PH7LZCX099H0XGS6_bl.bam"),
                               EML4_ALK_detection("1POXVH7P4YZ0N22P_bl.bam"),
                               EML4_ALK_detection("885S9KA6LW9I28H9_bl.bam"),
                               EML4_ALK_detection("YZ0PPZ1A5JLCB27C_bl.bam"),
                               EML4_ALK_detection("MONA_32.bam"),
                               EML4_ALK_detection("MONA_33.bam"),
                               EML4_ALK_detection("72EP6S90YZWUFGRT_bl.bam"),
                               EML4_ALK_detection("6KYRWVT7W2KW1U48_bl.bam"),
                               EML4_ALK_detection("UOOXOPI9BOLDIU56_bl.bam"),
                               EML4_ALK_detection("40U550ULPLYA0U5D_bl.bam"),
                               EML4_ALK_detection("9Y6DEL9FY4T37CX7_bl.bam"),
                               EML4_ALK_detection("YLRVNNYZ7D973YUL_bl.bam"),
                               EML4_ALK_detection("MONA_40.bam"),
                               EML4_ALK_detection("FDEDCZO3IR8TENC0_bl.bam"),
                               times = 20)
Monalec_positivity <- c("Positive", "Positive",
  "Negative", "Negative",
  "Negative", "Positive",
  "Negative", "Negative",
  "Positive", "Negative",
  "Positive", "Positive",
  "Negative", "Positive",
  "Negative", "Negative",
  "Positive", "Positive",
  "Positive", "Positive",
  "Positive", "Positive",
  "Positive", "Negative",
  "Positive", "Positive",
  "Positive", "Negative",
  "Positive", "Positive",
  "Negative", "Positive",
  "Positive", "Negative",
  "Negative", "Positive",
  "Negative", "Positive",
  "Positive", "Positive",
  "Negative")
#ff0066 negative
#108181 positive
setwd("C:/Users/Christoffer/OneDrive/1PhD/Manuskripter/DNAfusion/figures")
png(filename = "EML4_ALK-detection(), MonAlec.png",
    width = 7250,
    height = 6838,
    unit = "px",
    res = 1200)
boxplot(MonAlec_detection, xlab = "Patients",
        ylab = "log(time) (ms)",
        names = rep("", 41),
        col = c("#108181", "#108181",
                "#ff0066", "#ff0066",
                "#ff0066", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#ff0066",
                "#108181", "#108181",
                "#ff0066", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#108181",
                "#108181", "#108181",
                "#108181", "#108181",
                "#108181", "#ff0066",
                "#108181", "#108181",
                "#108181", "#ff0066",
                "#108181", "#108181",
                "#ff0066", "#108181",
                "#108181", "#ff0066",
                "#ff0066", "#108181",
                "#ff0066", "#108181",
                "#108181", "#108181",
                "#ff0066"),
        main = "EML4_ALK-detection(), MonAlec",
        cex.main=2, cex.lab=1.5, cex.sub=1.2)
legend("topright", legend = c("Positive", "Negative"),
                         fill = c("#108181", "#ff0066"),
       title = "EML4-ALK status")

dev.off()
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Maiken cohort/PosDeduped")
MonAlec_analysis <- microbenchmark::microbenchmark(EML4_ALK_analysis("00QWTDYUH1E0VRM8_bl.bam"),
                                                    EML4_ALK_analysis("9XPREVQOLXK3JE4S_bl.bam"),
                                                    EML4_ALK_analysis("CQHQ4QA5K295LU8D_bl.bam"),
                                                    EML4_ALK_analysis("Q54SLTX033G766IM_bl.bam"),
                                                    EML4_ALK_analysis("4M0SDUZCZMWHIYJ7_bl.bam"),
                                                    EML4_ALK_analysis("UE2R8PRMAT4T3IXD_bl.bam"),
                                                    EML4_ALK_analysis("IT8BJVO03C08FV04_bl.bam"),
                                                    EML4_ALK_analysis("YBNHFHWVB0HBC3YY_bl.bam"),
                                                    EML4_ALK_analysis("4OOA9FR46IB4BXBJ_bl.bam"),
                                                    EML4_ALK_analysis("G6M680NTHH1YGZ5A_bl.bam"),
                                                    EML4_ALK_analysis("OUWIO70E08Q51YTB_bl.bam"),
                                                    EML4_ALK_analysis("2UCZEDI4F35T6ILM_bl.bam"),
                                                    EML4_ALK_analysis("PQ9NESTYL82NBF9B_bl.bam"),
                                                    EML4_ALK_analysis("83Z7BF2N4Y12L933_bl.bam"),
                                                    EML4_ALK_analysis("91R09H85UBLFEOLO_bl.bam"),
                                                    EML4_ALK_analysis("K6YFO3FWXOFI99UZ_bl.bam"),
                                                    EML4_ALK_analysis("YNKZ9UW1EMNM7TQ5_bl.bam"),
                                                    EML4_ALK_analysis("5K04BRIUDO2EMCUM_bl.bam"),
                                                    EML4_ALK_analysis("MJ0ZS032J5A67ZUA_bl.bam"),
                                                    EML4_ALK_analysis("CMM8PC3S8M9NLOCH_bl.bam"),
                                                    EML4_ALK_analysis("UT3Y7U411B7L6GU0_bl.bam"),
                                                    EML4_ALK_analysis("B14Q10RS3BRU807A_bl.bam"),
                                                    EML4_ALK_analysis("YBWTPETM88I7OL5N_bl.bam"),
                                                    EML4_ALK_analysis("AEKYGMNC3109ZI9E_bl.bam"),
                                                    EML4_ALK_analysis("MONA_26.bam"),
                                                    EML4_ALK_analysis("SEAVIJ1HQS7PSXM1_bl.bam"),
                                                    EML4_ALK_analysis("PH7LZCX099H0XGS6_bl.bam"),
                                                    EML4_ALK_analysis("1POXVH7P4YZ0N22P_bl.bam"),
                                                    EML4_ALK_analysis("885S9KA6LW9I28H9_bl.bam"),
                                                    EML4_ALK_analysis("YZ0PPZ1A5JLCB27C_bl.bam"),
                                                    EML4_ALK_analysis("MONA_32.bam"),
                                                    EML4_ALK_analysis("MONA_33.bam"),
                                                    EML4_ALK_analysis("72EP6S90YZWUFGRT_bl.bam"),
                                                    EML4_ALK_analysis("6KYRWVT7W2KW1U48_bl.bam"),
                                                    EML4_ALK_analysis("UOOXOPI9BOLDIU56_bl.bam"),
                                                    EML4_ALK_analysis("40U550ULPLYA0U5D_bl.bam"),
                                                    EML4_ALK_analysis("9Y6DEL9FY4T37CX7_bl.bam"),
                                                    EML4_ALK_analysis("YLRVNNYZ7D973YUL_bl.bam"),
                                                    EML4_ALK_analysis("MONA_40.bam"),
                                                    EML4_ALK_analysis("FDEDCZO3IR8TENC0_bl.bam"),
                                                    times = 20)
setwd("C:/Users/Christoffer/OneDrive/1PhD/Manuskripter/DNAfusion/figures")
png(filename = "EML4_ALK-analysis(), MonAlec.png",
    width = 7250,
    height = 6838,
    unit = "px",
    res = 1200)

boxplot(MonAlec_analysis, xlab = "Patients",
        ylab = "log(time) (ms)",
        names = rep("", 40),
        col = c("#108181", "#108181",
                "#ff0066", "#ff0066",
                "#ff0066", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#ff0066",
                "#108181", "#108181",
                "#ff0066", "#108181",
                "#ff0066", "#ff0066",
                "#108181",
                "#108181", "#108181",
                "#108181", "#108181",
                "#108181", "#ff0066",
                "#108181", "#108181",
                "#108181", "#ff0066",
                "#108181", "#108181",
                "#ff0066", "#108181",
                "#108181", "#ff0066",
                "#ff0066", "#108181",
                "#ff0066", "#108181",
                "#108181", "#108181",
                "#ff0066"),
        main = "EML4_ALK-analysis(), MonAlec",
        cex.main=2, cex.lab=1.5, cex.sub=1.2,
        ylim = c(80,800))
legend("topright", legend = c("Positive", "Negative"),
       fill = c("#108181", "#ff0066"),
       title = "EML4-ALK status")
dev.off()
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Validation cohort")

Madsen_detection <- microbenchmark::microbenchmark(EML4_ALK_detection("PosDeduped-val01.bam"),
                                                   EML4_ALK_detection("PosDeduped-val02.bam"),
                                                   EML4_ALK_detection("PosDeduped-val06.bam"),
                                                   EML4_ALK_detection("PosDeduped-val09.bam"),
                                                   EML4_ALK_detection("PosDeduped-val10.bam"),
                                                   EML4_ALK_detection("PosDeduped-val14.bam"),
                                                   EML4_ALK_detection("PosDeduped-val15.bam"),
                                                   EML4_ALK_detection("PosDeduped-val16.bam"),
                                                   EML4_ALK_detection("PosDeduped-val18.bam"),
                                                   EML4_ALK_detection("PosDeduped-val20.bam"),
                                                   EML4_ALK_detection("PosDeduped-val21.bam"),
                                                   EML4_ALK_detection("PosDeduped-val25.bam"),
                                                   EML4_ALK_detection("PosDeduped-val26.bam"),
                                                   EML4_ALK_detection("PosDeduped-val30.bam"),
                                                   EML4_ALK_detection("PosDeduped-val31.bam"),
                                                   EML4_ALK_detection("PosDeduped-val32.bam"),
                                                   EML4_ALK_detection("PosDeduped-val33.bam"),
                                                   EML4_ALK_detection("PosDeduped-val34.bam"),
                                                   EML4_ALK_detection("PosDeduped-val37.bam"),
                                                   EML4_ALK_detection("PosDeduped-val38.bam"),
                                                   EML4_ALK_detection("PosDeduped-val39.bam"),
                                                   EML4_ALK_detection("PosDeduped-val42.bam"),
                                                   EML4_ALK_detection("PosDeduped-val43.bam"),
                                                   EML4_ALK_detection("PosDeduped-val47.bam"),
                                                   times = 20)
Madsen_positivity <- c("Negative", "Negative",
                       "Negative", "Positive",
                       "Positive", "Positive",
                       "Negative", "Negative",
                       "Positive", "Positive",
                       "Negative", "Negative",
                       "Positive", "Positive",
                       "Positive", "Positive",
                       "Positive", "Positive",
                       "Negative", "Positive",
                       "Positive", "Negative",
                       "Positive", "Positive")

#ff0066 negative
#108181 positive
setwd("C:/Users/Christoffer/OneDrive/1PhD/Manuskripter/DNAfusion/figures")
png(filename = "EML4_ALK-dection(), Madsen.png",
    width = 7250,
    height = 6838,
    unit = "px",
    res = 1200)

boxplot(Madsen_detection, xlab = "Patients",
        ylab = "log(time) (ms)",
        names = rep("", 24),
        col = c("#ff0066", "#ff0066",
                "#ff0066", "#108181",
                "#108181", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#108181",
                "#108181", "#108181",
                "#108181", "#108181",
                "#ff0066", "#108181",
                "#108181", "#ff0066",
                "#108181", "#108181"),
        main = "EML4_ALK-detection(), Madsen",
        cex.main=2, cex.lab=1.5, cex.sub=1.2)
legend("topright", legend = c("Positive", "Negative"),
       fill = c("#108181", "#ff0066"),
       title = "EML4-ALK status")
dev.off()
setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Validation cohort")
Madsen_analysis <- microbenchmark::microbenchmark(EML4_ALK_analysis("PosDeduped-val01.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val02.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val06.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val09.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val10.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val14.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val15.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val16.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val18.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val20.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val21.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val25.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val26.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val30.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val31.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val32.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val33.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val37.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val38.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val39.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val42.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val43.bam"),
                                                   EML4_ALK_analysis("PosDeduped-val47.bam"),
                                                   times = 20)
setwd("C:/Users/Christoffer/OneDrive/1PhD/Manuskripter/DNAfusion/figures")
png(filename = "EML4_ALK-analysis(), Madsen.png",
    width = 7250,
    height = 6838,
    unit = "px",
    res = 1200)
boxplot(Madsen_analysis, xlab = "Patients",
        ylab = "log(time) (ms)",
        names = rep("", 23),
        col = c("#ff0066", "#ff0066",
                "#ff0066", "#108181",
                "#108181", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#108181",
                "#ff0066", "#ff0066",
                "#108181", "#108181",
                "#108181", "#108181",
                "#108181",
                "#ff0066", "#108181",
                "#108181", "#ff0066",
                "#108181", "#108181"),
        main = "EML4_ALK-analysis(), Madsen",
        cex.main=2, cex.lab=1.5, cex.sub=1.2)
legend("topright", legend = c("Positive", "Negative"),
       fill = c("#108181", "#ff0066"),
       title = "EML4-ALK status")
dev.off()
