setwd("C:/Users/Christoffer/OneDrive/1PhD/ALK_patienter/Validation cohort")

library(DNAfusion)

####Detection####
EML4_ALK_detection("PosDeduped-val01.bam")
EML4_ALK_detection("PosDeduped-val02.bam")
EML4_ALK_detection("PosDeduped-val03.bam")
EML4_ALK_detection("PosDeduped-val04.bam")
EML4_ALK_detection("PosDeduped-val05.bam")
EML4_ALK_detection("PosDeduped-val06.bam")
EML4_ALK_detection("PosDeduped-val07.bam")
EML4_ALK_detection("PosDeduped-val08.bam")
EML4_ALK_detection("PosDeduped-val09.bam")
EML4_ALK_detection("PosDeduped-val10.bam")
EML4_ALK_detection("PosDeduped-val11.bam")
EML4_ALK_detection("PosDeduped-val12.bam")
EML4_ALK_detection("PosDeduped-val13.bam")
EML4_ALK_detection("PosDeduped-val14.bam")
EML4_ALK_detection("PosDeduped-val15.bam")
EML4_ALK_detection("PosDeduped-val16.bam")
EML4_ALK_detection("PosDeduped-val17.bam")
EML4_ALK_detection("PosDeduped-val18.bam")
EML4_ALK_detection("PosDeduped-val19.bam")
EML4_ALK_detection("PosDeduped-val20.bam")
EML4_ALK_detection("PosDeduped-val21.bam")
EML4_ALK_detection("PosDeduped-val22.bam")
EML4_ALK_detection("PosDeduped-val23.bam")
EML4_ALK_detection("PosDeduped-val24.bam")
EML4_ALK_detection("PosDeduped-val25.bam")
EML4_ALK_detection("PosDeduped-val26.bam")
EML4_ALK_detection("PosDeduped-val27.bam")
EML4_ALK_detection("PosDeduped-val28.bam")
EML4_ALK_detection("PosDeduped-val29.bam")
EML4_ALK_detection("PosDeduped-val30.bam")
EML4_ALK_detection("PosDeduped-val31.bam")
EML4_ALK_detection("PosDeduped-val32.bam")
EML4_ALK_detection("PosDeduped-val33.bam")
EML4_ALK_detection("PosDeduped-val34.bam")
EML4_ALK_detection("PosDeduped-val35.bam")
EML4_ALK_detection("PosDeduped-val36.bam")
EML4_ALK_detection("PosDeduped-val37.bam")
EML4_ALK_detection("PosDeduped-val38.bam")
EML4_ALK_detection("PosDeduped-val39.bam")
EML4_ALK_detection("PosDeduped-val40.bam")
EML4_ALK_detection("PosDeduped-val41.bam")
EML4_ALK_detection("PosDeduped-val42.bam")
EML4_ALK_detection("PosDeduped-val43.bam")
EML4_ALK_detection("PosDeduped-val44.bam")
EML4_ALK_detection("PosDeduped-val45.bam")
EML4_ALK_detection("PosDeduped-val46.bam")
EML4_ALK_detection("PosDeduped-val47.bam")
EML4_ALK_detection("PosDeduped-val48.bam")

####EML4_sequence####
EML4_sequence(EML4_ALK_detection("PosDeduped-val01.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val02.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val03.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val04.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val05.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val06.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val07.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val08.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val09.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val10.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val11.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val12.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val13.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val14.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val15.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val16.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val17.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val18.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val19.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val20.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val21.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val22.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val23.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val24.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val25.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val26.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val27.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val28.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val29.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val30.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val31.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val32.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val33.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val34.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val35.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val36.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val37.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val38.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val39.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val40.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val41.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val42.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val43.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val44.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val45.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val46.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val47.bam"))
EML4_sequence(EML4_ALK_detection("PosDeduped-val48.bam"))

####ALK_sequence####
ALK_sequence(EML4_ALK_detection("PosDeduped-val01.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val02.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val03.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val04.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val05.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val06.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val07.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val08.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val09.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val10.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val11.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val12.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val13.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val14.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val15.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val16.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val17.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val18.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val19.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val20.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val21.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val22.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val23.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val24.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val25.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val26.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val27.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val28.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val29.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val30.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val31.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val32.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val33.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val34.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val35.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val36.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val37.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val38.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val39.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val40.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val41.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val42.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val43.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val44.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val45.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val46.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val47.bam"))
ALK_sequence(EML4_ALK_detection("PosDeduped-val48.bam"))

####break_position####
break_position(EML4_ALK_detection("PosDeduped-val01.bam"))
break_position(EML4_ALK_detection("PosDeduped-val02.bam"))
break_position(EML4_ALK_detection("PosDeduped-val03.bam"))
break_position(EML4_ALK_detection("PosDeduped-val04.bam"))
break_position(EML4_ALK_detection("PosDeduped-val05.bam"))
break_position(EML4_ALK_detection("PosDeduped-val06.bam"))
break_position(EML4_ALK_detection("PosDeduped-val07.bam"))
break_position(EML4_ALK_detection("PosDeduped-val08.bam"))
break_position(EML4_ALK_detection("PosDeduped-val09.bam"))
break_position(EML4_ALK_detection("PosDeduped-val10.bam"))
break_position(EML4_ALK_detection("PosDeduped-val11.bam"))
break_position(EML4_ALK_detection("PosDeduped-val12.bam"))
break_position(EML4_ALK_detection("PosDeduped-val13.bam"))
break_position(EML4_ALK_detection("PosDeduped-val14.bam"))
break_position(EML4_ALK_detection("PosDeduped-val15.bam"))
break_position(EML4_ALK_detection("PosDeduped-val16.bam"))
break_position(EML4_ALK_detection("PosDeduped-val17.bam"))
break_position(EML4_ALK_detection("PosDeduped-val18.bam"))
break_position(EML4_ALK_detection("PosDeduped-val19.bam"))
break_position(EML4_ALK_detection("PosDeduped-val20.bam"))
break_position(EML4_ALK_detection("PosDeduped-val21.bam"))
break_position(EML4_ALK_detection("PosDeduped-val22.bam"))
break_position(EML4_ALK_detection("PosDeduped-val23.bam"))
break_position(EML4_ALK_detection("PosDeduped-val24.bam"))
break_position(EML4_ALK_detection("PosDeduped-val25.bam"))
break_position(EML4_ALK_detection("PosDeduped-val26.bam"))
break_position(EML4_ALK_detection("PosDeduped-val27.bam"))
break_position(EML4_ALK_detection("PosDeduped-val28.bam"))
break_position(EML4_ALK_detection("PosDeduped-val29.bam"))
break_position(EML4_ALK_detection("PosDeduped-val30.bam"))
break_position(EML4_ALK_detection("PosDeduped-val31.bam"))
break_position(EML4_ALK_detection("PosDeduped-val32.bam"))
break_position(EML4_ALK_detection("PosDeduped-val33.bam"))
break_position(EML4_ALK_detection("PosDeduped-val34.bam"))
break_position(EML4_ALK_detection("PosDeduped-val35.bam"))
break_position(EML4_ALK_detection("PosDeduped-val36.bam"))
break_position(EML4_ALK_detection("PosDeduped-val37.bam"))
break_position(EML4_ALK_detection("PosDeduped-val38.bam"))
break_position(EML4_ALK_detection("PosDeduped-val39.bam"))
break_position(EML4_ALK_detection("PosDeduped-val40.bam"))
break_position(EML4_ALK_detection("PosDeduped-val41.bam"))
break_position(EML4_ALK_detection("PosDeduped-val42.bam"))
break_position(EML4_ALK_detection("PosDeduped-val43.bam"))
break_position(EML4_ALK_detection("PosDeduped-val44.bam"))
break_position(EML4_ALK_detection("PosDeduped-val45.bam"))
break_position(EML4_ALK_detection("PosDeduped-val46.bam"))
break_position(EML4_ALK_detection("PosDeduped-val47.bam"))
break_position(EML4_ALK_detection("PosDeduped-val48.bam"))

####break_position_depth####
break_position_depth("PosDeduped-val01.bam", EML4_ALK_detection("PosDeduped-val01.bam"))
break_position_depth("PosDeduped-val02.bam", EML4_ALK_detection("PosDeduped-val02.bam"))
break_position_depth("PosDeduped-val03.bam", EML4_ALK_detection("PosDeduped-val03.bam"))
break_position_depth("PosDeduped-val04.bam", EML4_ALK_detection("PosDeduped-val04.bam"))
break_position_depth("PosDeduped-val05.bam", EML4_ALK_detection("PosDeduped-val05.bam"))
break_position_depth("PosDeduped-val06.bam", EML4_ALK_detection("PosDeduped-val06.bam"))
break_position_depth("PosDeduped-val07.bam", EML4_ALK_detection("PosDeduped-val07.bam"))
break_position_depth("PosDeduped-val08.bam", EML4_ALK_detection("PosDeduped-val08.bam"))
break_position_depth("PosDeduped-val09.bam", EML4_ALK_detection("PosDeduped-val09.bam"))
break_position_depth("PosDeduped-val10.bam", EML4_ALK_detection("PosDeduped-val10.bam"))
break_position_depth("PosDeduped-val11.bam", EML4_ALK_detection("PosDeduped-val11.bam"))
break_position_depth("PosDeduped-val12.bam", EML4_ALK_detection("PosDeduped-val12.bam"))
break_position_depth("PosDeduped-val13.bam", EML4_ALK_detection("PosDeduped-val13.bam"))
break_position_depth("PosDeduped-val14.bam", EML4_ALK_detection("PosDeduped-val14.bam"))
break_position_depth("PosDeduped-val15.bam", EML4_ALK_detection("PosDeduped-val15.bam"))
break_position_depth("PosDeduped-val16.bam", EML4_ALK_detection("PosDeduped-val16.bam"))
break_position_depth("PosDeduped-val17.bam", EML4_ALK_detection("PosDeduped-val17.bam"))
break_position_depth("PosDeduped-val18.bam", EML4_ALK_detection("PosDeduped-val18.bam"))
break_position_depth("PosDeduped-val19.bam", EML4_ALK_detection("PosDeduped-val19.bam"))
break_position_depth("PosDeduped-val20.bam", EML4_ALK_detection("PosDeduped-val20.bam"))
break_position_depth("PosDeduped-val21.bam", EML4_ALK_detection("PosDeduped-val21.bam"))
break_position_depth("PosDeduped-val22.bam", EML4_ALK_detection("PosDeduped-val22.bam"))
break_position_depth("PosDeduped-val23.bam", EML4_ALK_detection("PosDeduped-val23.bam"))
break_position_depth("PosDeduped-val24.bam", EML4_ALK_detection("PosDeduped-val24.bam"))
break_position_depth("PosDeduped-val25.bam", EML4_ALK_detection("PosDeduped-val25.bam"))
break_position_depth("PosDeduped-val26.bam", EML4_ALK_detection("PosDeduped-val26.bam"))
break_position_depth("PosDeduped-val27.bam", EML4_ALK_detection("PosDeduped-val27.bam"))
break_position_depth("PosDeduped-val28.bam", EML4_ALK_detection("PosDeduped-val28.bam"))
break_position_depth("PosDeduped-val29.bam", EML4_ALK_detection("PosDeduped-val29.bam"))
break_position_depth("PosDeduped-val30.bam", EML4_ALK_detection("PosDeduped-val30.bam"))
break_position_depth("PosDeduped-val31.bam", EML4_ALK_detection("PosDeduped-val31.bam"))
break_position_depth("PosDeduped-val32.bam", EML4_ALK_detection("PosDeduped-val32.bam"))
break_position_depth("PosDeduped-val33.bam", EML4_ALK_detection("PosDeduped-val33.bam"))
break_position_depth("PosDeduped-val34.bam", EML4_ALK_detection("PosDeduped-val34.bam"))
break_position_depth("PosDeduped-val35.bam", EML4_ALK_detection("PosDeduped-val35.bam"))
break_position_depth("PosDeduped-val36.bam", EML4_ALK_detection("PosDeduped-val36.bam"))
break_position_depth("PosDeduped-val37.bam", EML4_ALK_detection("PosDeduped-val37.bam"))
break_position_depth("PosDeduped-val38.bam", EML4_ALK_detection("PosDeduped-val38.bam"))
break_position_depth("PosDeduped-val39.bam", EML4_ALK_detection("PosDeduped-val39.bam"))
break_position_depth("PosDeduped-val40.bam", EML4_ALK_detection("PosDeduped-val40.bam"))
break_position_depth("PosDeduped-val41.bam", EML4_ALK_detection("PosDeduped-val41.bam"))
break_position_depth("PosDeduped-val42.bam", EML4_ALK_detection("PosDeduped-val42.bam"))
break_position_depth("PosDeduped-val43.bam", EML4_ALK_detection("PosDeduped-val43.bam"))
break_position_depth("PosDeduped-val44.bam", EML4_ALK_detection("PosDeduped-val44.bam"))
break_position_depth("PosDeduped-val45.bam", EML4_ALK_detection("PosDeduped-val45.bam"))
break_position_depth("PosDeduped-val46.bam", EML4_ALK_detection("PosDeduped-val46.bam"))
break_position_depth("PosDeduped-val47.bam", EML4_ALK_detection("PosDeduped-val47.bam"))
break_position_depth("PosDeduped-val48.bam", EML4_ALK_detection("PosDeduped-val48.bam"))

####EML4_ALK_analysis####
EML4_ALK_analysis("PosDeduped-val01.bam")
EML4_ALK_analysis("PosDeduped-val02.bam")
EML4_ALK_analysis("PosDeduped-val03.bam")
EML4_ALK_analysis("PosDeduped-val04.bam")
EML4_ALK_analysis("PosDeduped-val05.bam")
EML4_ALK_analysis("PosDeduped-val06.bam")
EML4_ALK_analysis("PosDeduped-val07.bam")
EML4_ALK_analysis("PosDeduped-val08.bam")
EML4_ALK_analysis("PosDeduped-val09.bam")
EML4_ALK_analysis("PosDeduped-val10.bam")
EML4_ALK_analysis("PosDeduped-val11.bam")
EML4_ALK_analysis("PosDeduped-val12.bam")
EML4_ALK_analysis("PosDeduped-val13.bam")
EML4_ALK_analysis("PosDeduped-val14.bam")
EML4_ALK_analysis("PosDeduped-val15.bam")
EML4_ALK_analysis("PosDeduped-val16.bam")
EML4_ALK_analysis("PosDeduped-val17.bam")
EML4_ALK_analysis("PosDeduped-val18.bam")
EML4_ALK_analysis("PosDeduped-val19.bam")
EML4_ALK_analysis("PosDeduped-val20.bam")
EML4_ALK_analysis("PosDeduped-val21.bam")
EML4_ALK_analysis("PosDeduped-val22.bam")
EML4_ALK_analysis("PosDeduped-val23.bam")
EML4_ALK_analysis("PosDeduped-val24.bam")
EML4_ALK_analysis("PosDeduped-val25.bam")
EML4_ALK_analysis("PosDeduped-val26.bam")
EML4_ALK_analysis("PosDeduped-val27.bam")
EML4_ALK_analysis("PosDeduped-val28.bam")
EML4_ALK_analysis("PosDeduped-val29.bam")
EML4_ALK_analysis("PosDeduped-val30.bam")
EML4_ALK_analysis("PosDeduped-val31.bam")
EML4_ALK_analysis("PosDeduped-val32.bam")
EML4_ALK_analysis("PosDeduped-val33.bam")
EML4_ALK_analysis("PosDeduped-val34.bam")
EML4_ALK_analysis("PosDeduped-val35.bam")
EML4_ALK_analysis("PosDeduped-val36.bam")
EML4_ALK_analysis("PosDeduped-val37.bam")
EML4_ALK_analysis("PosDeduped-val38.bam")
EML4_ALK_analysis("PosDeduped-val39.bam")
EML4_ALK_analysis("PosDeduped-val40.bam")
EML4_ALK_analysis("PosDeduped-val41.bam")
EML4_ALK_analysis("PosDeduped-val42.bam")
EML4_ALK_analysis("PosDeduped-val43.bam")
EML4_ALK_analysis("PosDeduped-val44.bam")
EML4_ALK_analysis("PosDeduped-val45.bam")
EML4_ALK_analysis("PosDeduped-val46.bam")
EML4_ALK_analysis("PosDeduped-val47.bam")
EML4_ALK_analysis("PosDeduped-val48.bam")
